import { beforeAll, describe, expect, it } from "vitest";
import { loadFrontendData } from "./frontend-data.server";
import { getAnalyticsView } from "./analytics";
import type { FrontendData } from "../types/solar";
let data: FrontendData;
beforeAll(async () => { data = await loadFrontendData(); });
describe("recorded analytics", () => {
  it("maps current KPIs", () => expect(getAnalyticsView(data).optimization.comparison).toMatchObject({currentAngle:35,recommendedAngle:45,predicted:6.09,movementCost:.03,netBenefit:.26}));
  it("keeps missing optimization null", () => expect(getAnalyticsView({...data,optimization:null}).optimization.comparison).toBeNull());
  it("orders candidate series by angle", () => expect(getAnalyticsView(data).optimization.candidates.map(c=>c.angle_deg)).toEqual([30,35,40,45,50,55,60]));
  it("supports no candidates", () => expect(getAnalyticsView({...data,candidate_predictions:[]}).optimization.candidates).toEqual([]));
  it("identifies current candidate", () => expect(getAnalyticsView(data).optimization.currentCandidate?.angle_deg).toBe(35));
  it("identifies recommendation", () => expect(getAnalyticsView(data).optimization.recommendedCandidate?.angle_deg).toBe(45));
  it("identifies raw max", () => expect(getAnalyticsView(data).optimization.rawMaxima).toEqual([{angle_deg:60,predicted_kwh:6.11}]));
  it("preserves tied raw maxima", () => expect(getAnalyticsView({...data,candidate_predictions:[{angle_deg:45,predicted_kwh:6},{angle_deg:60,predicted_kwh:6}]}).optimization.rawMaxima).toHaveLength(2));
  it("preserves canonical model collection", () => expect(getAnalyticsView(data).agents.models).toHaveLength(4));
  it("marks only backend-selected model", () => expect(getAnalyticsView(data).agents.models.filter(m=>m.selected).map(m=>m.model)).toEqual(["boosting"]));
  it("supports no selected model", () => expect(getAnalyticsView({...data,selected_model:null}).agents.selectedModel).toBeNull());
  it("keeps unavailable metrics unavailable", () => expect(getAnalyticsView({...data,model_comparison:[{...data.model_comparison[0],status:"UNAVAILABLE",mae:null,rmse:null,r2:null}]}).agents.models[0].metrics).toEqual(["—","—","—"]));
  it("counts row states", () => expect(getAnalyticsView(data).farm.states).toEqual({READY:48,MOVING:0,STOWED:2,FAULT:0}));
  it("counts recorded actions", () => expect(getAnalyticsView(data).farm.actions).toEqual({ROTATE:1,HOLD:47,STOW:2}));
  it("handles no rows", () => expect(getAnalyticsView({...data,farm_status:{...data.farm_status,rows:[]}}).rowCount).toBe(0));
  it("does not create missing history", () => expect(getAnalyticsView({...data,history:[]}).history).toEqual([]));
  it("preserves every historical record", () => expect(getAnalyticsView(data).history).toHaveLength(data.history.length));
  it("preserves recorded actions", () => expect(getAnalyticsView(data).history[0].decision).toEqual(data.history.at(-1)?.decision));
  it("preserves historical net benefit", () => expect(getAnalyticsView(data).history[0].net_benefit_kwh_equivalent).toBe(data.history.at(-1)?.net_benefit_kwh_equivalent));
  it("keeps current snapshot distinct", () => { const view=getAnalyticsView(data); expect(view.current.timestamp).toBe(data.timestamp); expect(view.history).not.toContainEqual(view.current); });
  it("does not mutate source order", () => { const before=JSON.stringify(data); getAnalyticsView(data); expect(JSON.stringify(data)).toBe(before); });
});
